version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: drone_postgres_db
    environment:
      POSTGRES_DB: DroneFleetDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    container_name: drone_fleet_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=DroneFleetDb;Username=postgres;Password=mysecretpassword
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: drone_fleet_frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    restart: always

volumes:
  pgdata:
