@Drone_Fleet_Monitor_HostAddress = http://localhost:8080

### ─────────────── GET ───────────────

GET {{Drone_Fleet_Monitor_HostAddress}}/api/drones
Accept: application/json

###
GET {{Drone_Fleet_Monitor_HostAddress}}/api/drones/civilian
Accept: application/json

###
GET {{Drone_Fleet_Monitor_HostAddress}}/api/drones/military
Accept: application/json

###
GET {{Drone_Fleet_Monitor_HostAddress}}/api/drones/1
Accept: application/json

### ─────────── POST civilian ───────────

# DeliveryDrone
POST {{Drone_Fleet_Monitor_HostAddress}}/api/drones/add?type=wingcopter198

###
# DeliveryDrone
POST {{Drone_Fleet_Monitor_HostAddress}}/api/drones/add?type=matternetm2

###
# SurveyDrone
POST {{Drone_Fleet_Monitor_HostAddress}}/api/drones/add?type=phantom4rtk

###
# SurveyDrone
POST {{Drone_Fleet_Monitor_HostAddress}}/api/drones/add?type=mavicenterprise

### ─────────── POST military ───────────

# ReconDrone
POST {{Drone_Fleet_Monitor_HostAddress}}/api/drones/add?type=bayraktartb2

###
# ReconDrone
POST {{Drone_Fleet_Monitor_HostAddress}}/api/drones/add?type=heron1

###
# CombatDrone
POST {{Drone_Fleet_Monitor_HostAddress}}/api/drones/add?type=mq9reaper

###
# CombatDrone
POST {{Drone_Fleet_Monitor_HostAddress}}/api/drones/add?type=bayraktarakinci

### ─────────────── PUT ───────────────

PUT {{Drone_Fleet_Monitor_HostAddress}}/api/drones/1/status?status=online

###
PUT {{Drone_Fleet_Monitor_HostAddress}}/api/drones/1/status?status=offline

###
PUT {{Drone_Fleet_Monitor_HostAddress}}/api/drones/1/name?name=Falcon%201

### ────────────── DELETE ──────────────

DELETE {{Drone_Fleet_Monitor_HostAddress}}/api/drones/1

###
# Reset
DELETE {{Drone_Fleet_Monitor_HostAddress}}/api/drones
