// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drone_Fleet_Monitor.Migrations
{
    [DbContext(typeof(DroneContext))]
    [Migration("20260725173342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drones.BaseDrone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Altitude")
                        .HasColumnType("real");

                    b.Property<float>("BatteryLevel")
                        .HasColumnType("real");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drones");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseDrone");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Drones.CombatDrone", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("CombatDrone");
                });

            modelBuilder.Entity("Drones.DeliveryDrone", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DeliveryDrone");
                });

            modelBuilder.Entity("Drones.ReconDrone", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Drones", t =>
                        {
                            t.Property("EncryptionKey")
                                .HasColumnName("ReconDrone_EncryptionKey");
                        });

                    b.HasDiscriminator().HasValue("ReconDrone");
                });

            modelBuilder.Entity("Drones.SurveyDrone", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Drones", t =>
                        {
                            t.Property("RegistrationNumber")
                                .HasColumnName("SurveyDrone_RegistrationNumber");
                        });

                    b.HasDiscriminator().HasValue("SurveyDrone");
                });

            modelBuilder.Entity("Drones.BaseDrone", b =>
                {
                    b.OwnsOne("Drones.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<int>("BaseDroneId")
                                .HasColumnType("integer");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("BaseDroneId");

                            b1.ToTable("Drones");

                            b1.WithOwner()
                                .HasForeignKey("BaseDroneId");
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
