// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drone_Fleet_Monitor.Migrations
{
    [DbContext(typeof(DroneContext))]
    [Migration("20260825230512_DroneModelTable")]
    partial class DroneModelTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drones.BaseDrone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("BatteryLevel")
                        .HasColumnType("real");

                    b.Property<int?>("DroneBaseId")
                        .HasColumnType("integer");

                    b.Property<int>("DroneModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParkedAtBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DroneBaseId");

                    b.HasIndex("DroneModelId");

                    b.HasIndex("ParkedAtBaseId");

                    b.ToTable("Drones");

                    b.HasDiscriminator<int>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Drones.DroneBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDroneCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxParkingCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bases");

                    b.HasDiscriminator<int>("Category");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Drones.DroneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("BatteryCapacity")
                        .HasColumnType("real");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<float>("MaxAltitude")
                        .HasColumnType("real");

                    b.Property<float>("MaxHorizontalSpeed")
                        .HasColumnType("real");

                    b.Property<float>("MaxVerticalSpeed")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DroneModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryCapacity = 12000f,
                            Category = 0,
                            ImagePath = "Images/DroneModels/Wingcopter198.png",
                            Kind = 0,
                            MaxAltitude = 4000f,
                            MaxHorizontalSpeed = 240f,
                            MaxVerticalSpeed = 15f,
                            Name = "Wingcopter198"
                        },
                        new
                        {
                            Id = 2,
                            BatteryCapacity = 5000f,
                            Category = 0,
                            ImagePath = "Images/DroneModels/MatternetM2.jpg",
                            Kind = 0,
                            MaxAltitude = 120f,
                            MaxHorizontalSpeed = 70f,
                            MaxVerticalSpeed = 5f,
                            Name = "MatternetM2"
                        },
                        new
                        {
                            Id = 3,
                            BatteryCapacity = 5870f,
                            Category = 0,
                            ImagePath = "Images/DroneModels/Phantom4RTK.jpeg",
                            Kind = 1,
                            MaxAltitude = 6000f,
                            MaxHorizontalSpeed = 72f,
                            MaxVerticalSpeed = 6f,
                            Name = "Phantom4RTK"
                        },
                        new
                        {
                            Id = 4,
                            BatteryCapacity = 5000f,
                            Category = 0,
                            ImagePath = "Images/DroneModels/MavicEnterprise.jpg",
                            Kind = 1,
                            MaxAltitude = 6000f,
                            MaxHorizontalSpeed = 72f,
                            MaxVerticalSpeed = 6f,
                            Name = "MavicEnterprise"
                        },
                        new
                        {
                            Id = 5,
                            BatteryCapacity = 20000f,
                            Category = 1,
                            ImagePath = "Images/DroneModels/BayraktarTB2.jpeg",
                            Kind = 2,
                            MaxAltitude = 8200f,
                            MaxHorizontalSpeed = 220f,
                            MaxVerticalSpeed = 12f,
                            Name = "BayraktarTB2"
                        },
                        new
                        {
                            Id = 6,
                            BatteryCapacity = 25000f,
                            Category = 1,
                            ImagePath = "Images/DroneModels/Heron1.jpeg",
                            Kind = 2,
                            MaxAltitude = 10000f,
                            MaxHorizontalSpeed = 207f,
                            MaxVerticalSpeed = 10f,
                            Name = "Heron1"
                        },
                        new
                        {
                            Id = 7,
                            BatteryCapacity = 30000f,
                            Category = 1,
                            ImagePath = "Images/DroneModels/MQ9Reaper.jpeg",
                            Kind = 3,
                            MaxAltitude = 15000f,
                            MaxHorizontalSpeed = 482f,
                            MaxVerticalSpeed = 25f,
                            Name = "MQ9Reaper"
                        },
                        new
                        {
                            Id = 8,
                            BatteryCapacity = 28000f,
                            Category = 1,
                            ImagePath = "Images/DroneModels/BayraktarAkinci.jpeg",
                            Kind = 3,
                            MaxAltitude = 12000f,
                            MaxHorizontalSpeed = 361f,
                            MaxVerticalSpeed = 20f,
                            Name = "BayraktarAkinci"
                        });
                });

            modelBuilder.Entity("Drones.CombatDrone", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Drones.DeliveryDrone", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Drones.ReconDrone", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Drones.SurveyDrone", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Drones.CivilianBase", b =>
                {
                    b.HasBaseType("Drones.DroneBase");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Drones.MilitaryBase", b =>
                {
                    b.HasBaseType("Drones.DroneBase");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Drones.BaseDrone", b =>
                {
                    b.HasOne("Drones.DroneBase", "HomeBase")
                        .WithMany("Drones")
                        .HasForeignKey("DroneBaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Drones.DroneModel", "DroneModel")
                        .WithMany()
                        .HasForeignKey("DroneModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drones.DroneBase", "ParkedAtBase")
                        .WithMany("ParkedDrones")
                        .HasForeignKey("ParkedAtBaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Drones.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<int>("BaseDroneId")
                                .HasColumnType("integer");

                            b1.Property<float>("Altitude")
                                .HasColumnType("real");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("BaseDroneId");

                            b1.ToTable("Drones");

                            b1.WithOwner()
                                .HasForeignKey("BaseDroneId");
                        });

                    b.OwnsOne("Drones.Speed", "CurrentSpeed", b1 =>
                        {
                            b1.Property<int>("BaseDroneId")
                                .HasColumnType("integer");

                            b1.Property<float>("Horizontal")
                                .HasColumnType("real");

                            b1.Property<float>("Vertical")
                                .HasColumnType("real");

                            b1.HasKey("BaseDroneId");

                            b1.ToTable("Drones");

                            b1.WithOwner()
                                .HasForeignKey("BaseDroneId");
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();

                    b.Navigation("CurrentSpeed")
                        .IsRequired();

                    b.Navigation("DroneModel");

                    b.Navigation("HomeBase");

                    b.Navigation("ParkedAtBase");
                });

            modelBuilder.Entity("Drones.DroneBase", b =>
                {
                    b.OwnsOne("Drones.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<int>("DroneBaseId")
                                .HasColumnType("integer");

                            b1.Property<float>("Altitude")
                                .HasColumnType("real");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("DroneBaseId");

                            b1.ToTable("Bases");

                            b1.WithOwner()
                                .HasForeignKey("DroneBaseId");
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Drones.DroneBase", b =>
                {
                    b.Navigation("Drones");

                    b.Navigation("ParkedDrones");
                });
#pragma warning restore 612, 618
        }
    }
}
