// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drone_Fleet_Monitor.Migrations
{
    [DbContext(typeof(DroneContext))]
    [Migration("20260824234611_ParkingCapacity")]
    partial class ParkingCapacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drones.BaseDrone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("BatteryLevel")
                        .HasColumnType("real");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int?>("DroneBaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Model")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParkedAtBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DroneBaseId");

                    b.HasIndex("ParkedAtBaseId");

                    b.ToTable("Drones");

                    b.HasDiscriminator<int>("Model");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Drones.DroneBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDroneCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxParkingCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bases");

                    b.HasDiscriminator<int>("Category");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Drones.BayraktarAkinci", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("Drones.BayraktarTB2", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Drones.Heron1", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Drones.MQ9Reaper", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Drones.MatternetM2", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Drones.MavicEnterprise", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Drones.Phantom4RTK", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Drones.Wingcopter198", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Drones.CivilianBase", b =>
                {
                    b.HasBaseType("Drones.DroneBase");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Drones.MilitaryBase", b =>
                {
                    b.HasBaseType("Drones.DroneBase");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Drones.BaseDrone", b =>
                {
                    b.HasOne("Drones.DroneBase", "HomeBase")
                        .WithMany("Drones")
                        .HasForeignKey("DroneBaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Drones.DroneBase", "ParkedAtBase")
                        .WithMany("ParkedDrones")
                        .HasForeignKey("ParkedAtBaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Drones.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<int>("BaseDroneId")
                                .HasColumnType("integer");

                            b1.Property<float>("Altitude")
                                .HasColumnType("real");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("BaseDroneId");

                            b1.ToTable("Drones");

                            b1.WithOwner()
                                .HasForeignKey("BaseDroneId");
                        });

                    b.OwnsOne("Drones.Speed", "CurrentSpeed", b1 =>
                        {
                            b1.Property<int>("BaseDroneId")
                                .HasColumnType("integer");

                            b1.Property<float>("Horizontal")
                                .HasColumnType("real");

                            b1.Property<float>("Vertical")
                                .HasColumnType("real");

                            b1.HasKey("BaseDroneId");

                            b1.ToTable("Drones");

                            b1.WithOwner()
                                .HasForeignKey("BaseDroneId");
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();

                    b.Navigation("CurrentSpeed")
                        .IsRequired();

                    b.Navigation("HomeBase");

                    b.Navigation("ParkedAtBase");
                });

            modelBuilder.Entity("Drones.DroneBase", b =>
                {
                    b.OwnsOne("Drones.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<int>("DroneBaseId")
                                .HasColumnType("integer");

                            b1.Property<float>("Altitude")
                                .HasColumnType("real");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("DroneBaseId");

                            b1.ToTable("Bases");

                            b1.WithOwner()
                                .HasForeignKey("DroneBaseId");
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Drones.DroneBase", b =>
                {
                    b.Navigation("Drones");

                    b.Navigation("ParkedDrones");
                });
#pragma warning restore 612, 618
        }
    }
}
