// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drone_Fleet_Monitor.Migrations
{
    [DbContext(typeof(DroneContext))]
    partial class DroneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drones.BaseDrone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("BatteryLevel")
                        .HasColumnType("real");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Model")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drones");

                    b.HasDiscriminator<int>("Model");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Drones.BayraktarAkinci", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("Drones.BayraktarTB2", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Drones.Heron1", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Drones.MQ9Reaper", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Drones.MatternetM2", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Drones.MavicEnterprise", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Drones.Phantom4RTK", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Drones.Wingcopter198", b =>
                {
                    b.HasBaseType("Drones.BaseDrone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Drones.BaseDrone", b =>
                {
                    b.OwnsOne("Drones.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<int>("BaseDroneId")
                                .HasColumnType("integer");

                            b1.Property<float>("Altitude")
                                .HasColumnType("real");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("BaseDroneId");

                            b1.ToTable("Drones");

                            b1.WithOwner()
                                .HasForeignKey("BaseDroneId");
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
